
spring:
  datasource:
    driverCLassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
    password: P@sser
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      show-sql: true
